version: "3"
services:
  restaurant-api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: